/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data;


import com.graphql.example.db.data.tables.Albums;
import com.graphql.example.db.data.tables.Artists;
import com.graphql.example.db.data.tables.Customers;
import com.graphql.example.db.data.tables.Employees;
import com.graphql.example.db.data.tables.Genres;
import com.graphql.example.db.data.tables.InvoiceItems;
import com.graphql.example.db.data.tables.Invoices;
import com.graphql.example.db.data.tables.MediaTypes;
import com.graphql.example.db.data.tables.PlaylistTrack;
import com.graphql.example.db.data.tables.Playlists;
import com.graphql.example.db.data.tables.SqliteSequence;
import com.graphql.example.db.data.tables.SqliteStat1;
import com.graphql.example.db.data.tables.Tracks;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1825856572;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>albums</code>.
     */
    public final Albums ALBUMS = com.graphql.example.db.data.tables.Albums.ALBUMS;

    /**
     * The table <code>artists</code>.
     */
    public final Artists ARTISTS = com.graphql.example.db.data.tables.Artists.ARTISTS;

    /**
     * The table <code>customers</code>.
     */
    public final Customers CUSTOMERS = com.graphql.example.db.data.tables.Customers.CUSTOMERS;

    /**
     * The table <code>employees</code>.
     */
    public final Employees EMPLOYEES = com.graphql.example.db.data.tables.Employees.EMPLOYEES;

    /**
     * The table <code>genres</code>.
     */
    public final Genres GENRES = com.graphql.example.db.data.tables.Genres.GENRES;

    /**
     * The table <code>invoice_items</code>.
     */
    public final InvoiceItems INVOICE_ITEMS = com.graphql.example.db.data.tables.InvoiceItems.INVOICE_ITEMS;

    /**
     * The table <code>invoices</code>.
     */
    public final Invoices INVOICES = com.graphql.example.db.data.tables.Invoices.INVOICES;

    /**
     * The table <code>media_types</code>.
     */
    public final MediaTypes MEDIA_TYPES = com.graphql.example.db.data.tables.MediaTypes.MEDIA_TYPES;

    /**
     * The table <code>playlist_track</code>.
     */
    public final PlaylistTrack PLAYLIST_TRACK = com.graphql.example.db.data.tables.PlaylistTrack.PLAYLIST_TRACK;

    /**
     * The table <code>playlists</code>.
     */
    public final Playlists PLAYLISTS = com.graphql.example.db.data.tables.Playlists.PLAYLISTS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public final SqliteSequence SQLITE_SEQUENCE = com.graphql.example.db.data.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>sqlite_stat1</code>.
     */
    public final SqliteStat1 SQLITE_STAT1 = com.graphql.example.db.data.tables.SqliteStat1.SQLITE_STAT1;

    /**
     * The table <code>tracks</code>.
     */
    public final Tracks TRACKS = com.graphql.example.db.data.tables.Tracks.TRACKS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Albums.ALBUMS,
            Artists.ARTISTS,
            Customers.CUSTOMERS,
            Employees.EMPLOYEES,
            Genres.GENRES,
            InvoiceItems.INVOICE_ITEMS,
            Invoices.INVOICES,
            MediaTypes.MEDIA_TYPES,
            PlaylistTrack.PLAYLIST_TRACK,
            Playlists.PLAYLISTS,
            SqliteSequence.SQLITE_SEQUENCE,
            SqliteStat1.SQLITE_STAT1,
            Tracks.TRACKS);
    }
}
