/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data;


import com.graphql.example.db.data.tables.Albums;
import com.graphql.example.db.data.tables.Customers;
import com.graphql.example.db.data.tables.Employees;
import com.graphql.example.db.data.tables.InvoiceItems;
import com.graphql.example.db.data.tables.Invoices;
import com.graphql.example.db.data.tables.PlaylistTrack;
import com.graphql.example.db.data.tables.Tracks;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IFK_ALBUMARTISTID = Indexes0.IFK_ALBUMARTISTID;
    public static final Index IFK_CUSTOMERSUPPORTREPID = Indexes0.IFK_CUSTOMERSUPPORTREPID;
    public static final Index IFK_EMPLOYEEREPORTSTO = Indexes0.IFK_EMPLOYEEREPORTSTO;
    public static final Index IFK_INVOICELINEINVOICEID = Indexes0.IFK_INVOICELINEINVOICEID;
    public static final Index IFK_INVOICELINETRACKID = Indexes0.IFK_INVOICELINETRACKID;
    public static final Index IFK_INVOICECUSTOMERID = Indexes0.IFK_INVOICECUSTOMERID;
    public static final Index IFK_PLAYLISTTRACKTRACKID = Indexes0.IFK_PLAYLISTTRACKTRACKID;
    public static final Index SQLITE_AUTOINDEX_PLAYLIST_TRACK_1 = Indexes0.SQLITE_AUTOINDEX_PLAYLIST_TRACK_1;
    public static final Index IFK_TRACKALBUMID = Indexes0.IFK_TRACKALBUMID;
    public static final Index IFK_TRACKGENREID = Indexes0.IFK_TRACKGENREID;
    public static final Index IFK_TRACKMEDIATYPEID = Indexes0.IFK_TRACKMEDIATYPEID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index IFK_ALBUMARTISTID = createIndex("IFK_AlbumArtistId", Albums.ALBUMS, new OrderField[] { Albums.ALBUMS.ARTISTID }, false);
        public static Index IFK_CUSTOMERSUPPORTREPID = createIndex("IFK_CustomerSupportRepId", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.SUPPORTREPID }, false);
        public static Index IFK_EMPLOYEEREPORTSTO = createIndex("IFK_EmployeeReportsTo", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.REPORTSTO }, false);
        public static Index IFK_INVOICELINEINVOICEID = createIndex("IFK_InvoiceLineInvoiceId", InvoiceItems.INVOICE_ITEMS, new OrderField[] { InvoiceItems.INVOICE_ITEMS.INVOICEID }, false);
        public static Index IFK_INVOICELINETRACKID = createIndex("IFK_InvoiceLineTrackId", InvoiceItems.INVOICE_ITEMS, new OrderField[] { InvoiceItems.INVOICE_ITEMS.TRACKID }, false);
        public static Index IFK_INVOICECUSTOMERID = createIndex("IFK_InvoiceCustomerId", Invoices.INVOICES, new OrderField[] { Invoices.INVOICES.CUSTOMERID }, false);
        public static Index IFK_PLAYLISTTRACKTRACKID = createIndex("IFK_PlaylistTrackTrackId", PlaylistTrack.PLAYLIST_TRACK, new OrderField[] { PlaylistTrack.PLAYLIST_TRACK.TRACKID }, false);
        public static Index SQLITE_AUTOINDEX_PLAYLIST_TRACK_1 = createIndex("sqlite_autoindex_playlist_track_1", PlaylistTrack.PLAYLIST_TRACK, new OrderField[] { PlaylistTrack.PLAYLIST_TRACK.PLAYLISTID, PlaylistTrack.PLAYLIST_TRACK.TRACKID }, true);
        public static Index IFK_TRACKALBUMID = createIndex("IFK_TrackAlbumId", Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.ALBUMID }, false);
        public static Index IFK_TRACKGENREID = createIndex("IFK_TrackGenreId", Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.GENREID }, false);
        public static Index IFK_TRACKMEDIATYPEID = createIndex("IFK_TrackMediaTypeId", Tracks.TRACKS, new OrderField[] { Tracks.TRACKS.MEDIATYPEID }, false);
    }
}
