/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data;


import com.graphql.example.db.data.tables.Albums;
import com.graphql.example.db.data.tables.Artists;
import com.graphql.example.db.data.tables.Customers;
import com.graphql.example.db.data.tables.Employees;
import com.graphql.example.db.data.tables.Genres;
import com.graphql.example.db.data.tables.InvoiceItems;
import com.graphql.example.db.data.tables.Invoices;
import com.graphql.example.db.data.tables.MediaTypes;
import com.graphql.example.db.data.tables.PlaylistTrack;
import com.graphql.example.db.data.tables.Playlists;
import com.graphql.example.db.data.tables.SqliteSequence;
import com.graphql.example.db.data.tables.SqliteStat1;
import com.graphql.example.db.data.tables.Tracks;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>albums</code>.
     */
    public static final Albums ALBUMS = com.graphql.example.db.data.tables.Albums.ALBUMS;

    /**
     * The table <code>artists</code>.
     */
    public static final Artists ARTISTS = com.graphql.example.db.data.tables.Artists.ARTISTS;

    /**
     * The table <code>customers</code>.
     */
    public static final Customers CUSTOMERS = com.graphql.example.db.data.tables.Customers.CUSTOMERS;

    /**
     * The table <code>employees</code>.
     */
    public static final Employees EMPLOYEES = com.graphql.example.db.data.tables.Employees.EMPLOYEES;

    /**
     * The table <code>genres</code>.
     */
    public static final Genres GENRES = com.graphql.example.db.data.tables.Genres.GENRES;

    /**
     * The table <code>invoice_items</code>.
     */
    public static final InvoiceItems INVOICE_ITEMS = com.graphql.example.db.data.tables.InvoiceItems.INVOICE_ITEMS;

    /**
     * The table <code>invoices</code>.
     */
    public static final Invoices INVOICES = com.graphql.example.db.data.tables.Invoices.INVOICES;

    /**
     * The table <code>media_types</code>.
     */
    public static final MediaTypes MEDIA_TYPES = com.graphql.example.db.data.tables.MediaTypes.MEDIA_TYPES;

    /**
     * The table <code>playlist_track</code>.
     */
    public static final PlaylistTrack PLAYLIST_TRACK = com.graphql.example.db.data.tables.PlaylistTrack.PLAYLIST_TRACK;

    /**
     * The table <code>playlists</code>.
     */
    public static final Playlists PLAYLISTS = com.graphql.example.db.data.tables.Playlists.PLAYLISTS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = com.graphql.example.db.data.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>sqlite_stat1</code>.
     */
    public static final SqliteStat1 SQLITE_STAT1 = com.graphql.example.db.data.tables.SqliteStat1.SQLITE_STAT1;

    /**
     * The table <code>tracks</code>.
     */
    public static final Tracks TRACKS = com.graphql.example.db.data.tables.Tracks.TRACKS;
}
