/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data.tables.records;


import com.graphql.example.db.data.tables.Customers;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> implements Record13<Integer, String, String, String, String, String, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 487199761;

    /**
     * Setter for <code>customers.CustomerId</code>.
     */
    public void setCustomerid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>customers.CustomerId</code>.
     */
    public Integer getCustomerid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>customers.FirstName</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>customers.FirstName</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>customers.LastName</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>customers.LastName</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>customers.Company</code>.
     */
    public void setCompany(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>customers.Company</code>.
     */
    public String getCompany() {
        return (String) get(3);
    }

    /**
     * Setter for <code>customers.Address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>customers.Address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>customers.City</code>.
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>customers.City</code>.
     */
    public String getCity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>customers.State</code>.
     */
    public void setState(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>customers.State</code>.
     */
    public String getState() {
        return (String) get(6);
    }

    /**
     * Setter for <code>customers.Country</code>.
     */
    public void setCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>customers.Country</code>.
     */
    public String getCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>customers.PostalCode</code>.
     */
    public void setPostalcode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>customers.PostalCode</code>.
     */
    public String getPostalcode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>customers.Phone</code>.
     */
    public void setPhone(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>customers.Phone</code>.
     */
    public String getPhone() {
        return (String) get(9);
    }

    /**
     * Setter for <code>customers.Fax</code>.
     */
    public void setFax(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>customers.Fax</code>.
     */
    public String getFax() {
        return (String) get(10);
    }

    /**
     * Setter for <code>customers.Email</code>.
     */
    public void setEmail(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>customers.Email</code>.
     */
    public String getEmail() {
        return (String) get(11);
    }

    /**
     * Setter for <code>customers.SupportRepId</code>.
     */
    public void setSupportrepid(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>customers.SupportRepId</code>.
     */
    public Integer getSupportrepid() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, String, String, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Customers.CUSTOMERS.CUSTOMERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Customers.CUSTOMERS.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Customers.CUSTOMERS.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Customers.CUSTOMERS.COMPANY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Customers.CUSTOMERS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Customers.CUSTOMERS.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Customers.CUSTOMERS.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Customers.CUSTOMERS.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Customers.CUSTOMERS.POSTALCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Customers.CUSTOMERS.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Customers.CUSTOMERS.FAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Customers.CUSTOMERS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Customers.CUSTOMERS.SUPPORTREPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCompany();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getFax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getSupportrepid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCompany();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getSupportrepid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value1(Integer value) {
        setCustomerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value2(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value3(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value4(String value) {
        setCompany(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value5(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value6(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value7(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value8(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value9(String value) {
        setPostalcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value10(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value11(String value) {
        setFax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value12(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord value13(Integer value) {
        setSupportrepid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomersRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Integer customerid, String firstname, String lastname, String company, String address, String city, String state, String country, String postalcode, String phone, String fax, String email, Integer supportrepid) {
        super(Customers.CUSTOMERS);

        set(0, customerid);
        set(1, firstname);
        set(2, lastname);
        set(3, company);
        set(4, address);
        set(5, city);
        set(6, state);
        set(7, country);
        set(8, postalcode);
        set(9, phone);
        set(10, fax);
        set(11, email);
        set(12, supportrepid);
    }
}
