/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data.tables.records;


import com.graphql.example.db.data.tables.Employees;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesRecord extends UpdatableRecordImpl<EmployeesRecord> implements Record15<Integer, String, String, String, Integer, Timestamp, Timestamp, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 76151007;

    /**
     * Setter for <code>employees.EmployeeId</code>.
     */
    public void setEmployeeid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>employees.EmployeeId</code>.
     */
    public Integer getEmployeeid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>employees.LastName</code>.
     */
    public void setLastname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>employees.LastName</code>.
     */
    public String getLastname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>employees.FirstName</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>employees.FirstName</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>employees.Title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>employees.Title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>employees.ReportsTo</code>.
     */
    public void setReportsto(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>employees.ReportsTo</code>.
     */
    public Integer getReportsto() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>employees.BirthDate</code>.
     */
    public void setBirthdate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>employees.BirthDate</code>.
     */
    public Timestamp getBirthdate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>employees.HireDate</code>.
     */
    public void setHiredate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>employees.HireDate</code>.
     */
    public Timestamp getHiredate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>employees.Address</code>.
     */
    public void setAddress(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>employees.Address</code>.
     */
    public String getAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>employees.City</code>.
     */
    public void setCity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>employees.City</code>.
     */
    public String getCity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>employees.State</code>.
     */
    public void setState(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>employees.State</code>.
     */
    public String getState() {
        return (String) get(9);
    }

    /**
     * Setter for <code>employees.Country</code>.
     */
    public void setCountry(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>employees.Country</code>.
     */
    public String getCountry() {
        return (String) get(10);
    }

    /**
     * Setter for <code>employees.PostalCode</code>.
     */
    public void setPostalcode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>employees.PostalCode</code>.
     */
    public String getPostalcode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>employees.Phone</code>.
     */
    public void setPhone(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>employees.Phone</code>.
     */
    public String getPhone() {
        return (String) get(12);
    }

    /**
     * Setter for <code>employees.Fax</code>.
     */
    public void setFax(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>employees.Fax</code>.
     */
    public String getFax() {
        return (String) get(13);
    }

    /**
     * Setter for <code>employees.Email</code>.
     */
    public void setEmail(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>employees.Email</code>.
     */
    public String getEmail() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, Integer, Timestamp, Timestamp, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, Integer, Timestamp, Timestamp, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Employees.EMPLOYEES.EMPLOYEEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Employees.EMPLOYEES.LASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Employees.EMPLOYEES.FIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Employees.EMPLOYEES.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Employees.EMPLOYEES.REPORTSTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Employees.EMPLOYEES.BIRTHDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Employees.EMPLOYEES.HIREDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Employees.EMPLOYEES.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Employees.EMPLOYEES.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Employees.EMPLOYEES.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Employees.EMPLOYEES.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Employees.EMPLOYEES.POSTALCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Employees.EMPLOYEES.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Employees.EMPLOYEES.FAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Employees.EMPLOYEES.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getEmployeeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getReportsto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getHiredate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getFax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getEmployeeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getReportsto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getBirthdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getHiredate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getPostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getFax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value1(Integer value) {
        setEmployeeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value2(String value) {
        setLastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value4(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value5(Integer value) {
        setReportsto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value6(Timestamp value) {
        setBirthdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value7(Timestamp value) {
        setHiredate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value8(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value9(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value10(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value11(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value12(String value) {
        setPostalcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value13(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value14(String value) {
        setFax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value15(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Timestamp value6, Timestamp value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(Integer employeeid, String lastname, String firstname, String title, Integer reportsto, Timestamp birthdate, Timestamp hiredate, String address, String city, String state, String country, String postalcode, String phone, String fax, String email) {
        super(Employees.EMPLOYEES);

        set(0, employeeid);
        set(1, lastname);
        set(2, firstname);
        set(3, title);
        set(4, reportsto);
        set(5, birthdate);
        set(6, hiredate);
        set(7, address);
        set(8, city);
        set(9, state);
        set(10, country);
        set(11, postalcode);
        set(12, phone);
        set(13, fax);
        set(14, email);
    }
}
