/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data.tables.records;


import com.graphql.example.db.data.tables.InvoiceItems;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceItemsRecord extends UpdatableRecordImpl<InvoiceItemsRecord> implements Record5<Integer, Integer, Integer, BigDecimal, Integer> {

    private static final long serialVersionUID = 1764306722;

    /**
     * Setter for <code>invoice_items.InvoiceLineId</code>.
     */
    public void setInvoicelineid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>invoice_items.InvoiceLineId</code>.
     */
    public Integer getInvoicelineid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>invoice_items.InvoiceId</code>.
     */
    public void setInvoiceid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>invoice_items.InvoiceId</code>.
     */
    public Integer getInvoiceid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>invoice_items.TrackId</code>.
     */
    public void setTrackid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>invoice_items.TrackId</code>.
     */
    public Integer getTrackid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>invoice_items.UnitPrice</code>.
     */
    public void setUnitprice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>invoice_items.UnitPrice</code>.
     */
    public BigDecimal getUnitprice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>invoice_items.Quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>invoice_items.Quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, BigDecimal, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, BigDecimal, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InvoiceItems.INVOICE_ITEMS.INVOICELINEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return InvoiceItems.INVOICE_ITEMS.INVOICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return InvoiceItems.INVOICE_ITEMS.TRACKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return InvoiceItems.INVOICE_ITEMS.UNITPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return InvoiceItems.INVOICE_ITEMS.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getInvoicelineid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getInvoiceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTrackid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getUnitprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getInvoicelineid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getInvoiceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTrackid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getUnitprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceItemsRecord value1(Integer value) {
        setInvoicelineid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceItemsRecord value2(Integer value) {
        setInvoiceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceItemsRecord value3(Integer value) {
        setTrackid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceItemsRecord value4(BigDecimal value) {
        setUnitprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceItemsRecord value5(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoiceItemsRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceItemsRecord
     */
    public InvoiceItemsRecord() {
        super(InvoiceItems.INVOICE_ITEMS);
    }

    /**
     * Create a detached, initialised InvoiceItemsRecord
     */
    public InvoiceItemsRecord(Integer invoicelineid, Integer invoiceid, Integer trackid, BigDecimal unitprice, Integer quantity) {
        super(InvoiceItems.INVOICE_ITEMS);

        set(0, invoicelineid);
        set(1, invoiceid);
        set(2, trackid);
        set(3, unitprice);
        set(4, quantity);
    }
}
