/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data.tables.records;


import com.graphql.example.db.data.tables.Invoices;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoicesRecord extends UpdatableRecordImpl<InvoicesRecord> implements Record9<Integer, Integer, Timestamp, String, String, String, String, String, BigDecimal> {

    private static final long serialVersionUID = 1856781606;

    /**
     * Setter for <code>invoices.InvoiceId</code>.
     */
    public void setInvoiceid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>invoices.InvoiceId</code>.
     */
    public Integer getInvoiceid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>invoices.CustomerId</code>.
     */
    public void setCustomerid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>invoices.CustomerId</code>.
     */
    public Integer getCustomerid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>invoices.InvoiceDate</code>.
     */
    public void setInvoicedate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>invoices.InvoiceDate</code>.
     */
    public Timestamp getInvoicedate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>invoices.BillingAddress</code>.
     */
    public void setBillingaddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>invoices.BillingAddress</code>.
     */
    public String getBillingaddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>invoices.BillingCity</code>.
     */
    public void setBillingcity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>invoices.BillingCity</code>.
     */
    public String getBillingcity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>invoices.BillingState</code>.
     */
    public void setBillingstate(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>invoices.BillingState</code>.
     */
    public String getBillingstate() {
        return (String) get(5);
    }

    /**
     * Setter for <code>invoices.BillingCountry</code>.
     */
    public void setBillingcountry(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>invoices.BillingCountry</code>.
     */
    public String getBillingcountry() {
        return (String) get(6);
    }

    /**
     * Setter for <code>invoices.BillingPostalCode</code>.
     */
    public void setBillingpostalcode(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>invoices.BillingPostalCode</code>.
     */
    public String getBillingpostalcode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>invoices.Total</code>.
     */
    public void setTotal(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>invoices.Total</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Timestamp, String, String, String, String, String, BigDecimal> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Timestamp, String, String, String, String, String, BigDecimal> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Invoices.INVOICES.INVOICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Invoices.INVOICES.CUSTOMERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Invoices.INVOICES.INVOICEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Invoices.INVOICES.BILLINGADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Invoices.INVOICES.BILLINGCITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Invoices.INVOICES.BILLINGSTATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Invoices.INVOICES.BILLINGCOUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Invoices.INVOICES.BILLINGPOSTALCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return Invoices.INVOICES.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getInvoiceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getInvoicedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getBillingaddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBillingcity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getBillingstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getBillingcountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getBillingpostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getInvoiceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getInvoicedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBillingaddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBillingcity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBillingstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getBillingcountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBillingpostalcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value1(Integer value) {
        setInvoiceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value2(Integer value) {
        setCustomerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value3(Timestamp value) {
        setInvoicedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value4(String value) {
        setBillingaddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value5(String value) {
        setBillingcity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value6(String value) {
        setBillingstate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value7(String value) {
        setBillingcountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value8(String value) {
        setBillingpostalcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value9(BigDecimal value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord values(Integer value1, Integer value2, Timestamp value3, String value4, String value5, String value6, String value7, String value8, BigDecimal value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoicesRecord
     */
    public InvoicesRecord() {
        super(Invoices.INVOICES);
    }

    /**
     * Create a detached, initialised InvoicesRecord
     */
    public InvoicesRecord(Integer invoiceid, Integer customerid, Timestamp invoicedate, String billingaddress, String billingcity, String billingstate, String billingcountry, String billingpostalcode, BigDecimal total) {
        super(Invoices.INVOICES);

        set(0, invoiceid);
        set(1, customerid);
        set(2, invoicedate);
        set(3, billingaddress);
        set(4, billingcity);
        set(5, billingstate);
        set(6, billingcountry);
        set(7, billingpostalcode);
        set(8, total);
    }
}
