/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data.tables.records;


import com.graphql.example.db.data.tables.Playlists;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaylistsRecord extends UpdatableRecordImpl<PlaylistsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -42932912;

    /**
     * Setter for <code>playlists.PlaylistId</code>.
     */
    public void setPlaylistid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>playlists.PlaylistId</code>.
     */
    public Integer getPlaylistid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>playlists.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>playlists.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Playlists.PLAYLISTS.PLAYLISTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Playlists.PLAYLISTS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPlaylistid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPlaylistid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaylistsRecord value1(Integer value) {
        setPlaylistid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaylistsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaylistsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaylistsRecord
     */
    public PlaylistsRecord() {
        super(Playlists.PLAYLISTS);
    }

    /**
     * Create a detached, initialised PlaylistsRecord
     */
    public PlaylistsRecord(Integer playlistid, String name) {
        super(Playlists.PLAYLISTS);

        set(0, playlistid);
        set(1, name);
    }
}
