/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data.tables.records;


import com.graphql.example.db.data.tables.PlaylistTrack;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaylistTrackRecord extends UpdatableRecordImpl<PlaylistTrackRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 616707963;

    /**
     * Setter for <code>playlist_track.PlaylistId</code>.
     */
    public void setPlaylistid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>playlist_track.PlaylistId</code>.
     */
    public Integer getPlaylistid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>playlist_track.TrackId</code>.
     */
    public void setTrackid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>playlist_track.TrackId</code>.
     */
    public Integer getTrackid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PlaylistTrack.PLAYLIST_TRACK.PLAYLISTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PlaylistTrack.PLAYLIST_TRACK.TRACKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPlaylistid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTrackid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPlaylistid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTrackid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaylistTrackRecord value1(Integer value) {
        setPlaylistid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaylistTrackRecord value2(Integer value) {
        setTrackid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaylistTrackRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaylistTrackRecord
     */
    public PlaylistTrackRecord() {
        super(PlaylistTrack.PLAYLIST_TRACK);
    }

    /**
     * Create a detached, initialised PlaylistTrackRecord
     */
    public PlaylistTrackRecord(Integer playlistid, Integer trackid) {
        super(PlaylistTrack.PLAYLIST_TRACK);

        set(0, playlistid);
        set(1, trackid);
    }
}
