/*
 * This file is generated by jOOQ.
*/
package com.graphql.example.db.data.tables.records;


import com.graphql.example.db.data.tables.Tracks;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TracksRecord extends UpdatableRecordImpl<TracksRecord> implements Record9<Integer, String, Integer, Integer, Integer, String, Integer, Integer, BigDecimal> {

    private static final long serialVersionUID = 484829960;

    /**
     * Setter for <code>tracks.TrackId</code>.
     */
    public void setTrackid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tracks.TrackId</code>.
     */
    public Integer getTrackid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tracks.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tracks.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tracks.AlbumId</code>.
     */
    public void setAlbumid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>tracks.AlbumId</code>.
     */
    public Integer getAlbumid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>tracks.MediaTypeId</code>.
     */
    public void setMediatypeid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>tracks.MediaTypeId</code>.
     */
    public Integer getMediatypeid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>tracks.GenreId</code>.
     */
    public void setGenreid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>tracks.GenreId</code>.
     */
    public Integer getGenreid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>tracks.Composer</code>.
     */
    public void setComposer(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tracks.Composer</code>.
     */
    public String getComposer() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tracks.Milliseconds</code>.
     */
    public void setMilliseconds(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>tracks.Milliseconds</code>.
     */
    public Integer getMilliseconds() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>tracks.Bytes</code>.
     */
    public void setBytes(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>tracks.Bytes</code>.
     */
    public Integer getBytes() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>tracks.UnitPrice</code>.
     */
    public void setUnitprice(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>tracks.UnitPrice</code>.
     */
    public BigDecimal getUnitprice() {
        return (BigDecimal) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, Integer, String, Integer, Integer, BigDecimal> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, Integer, String, Integer, Integer, BigDecimal> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tracks.TRACKS.TRACKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tracks.TRACKS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Tracks.TRACKS.ALBUMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Tracks.TRACKS.MEDIATYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Tracks.TRACKS.GENREID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Tracks.TRACKS.COMPOSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Tracks.TRACKS.MILLISECONDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Tracks.TRACKS.BYTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return Tracks.TRACKS.UNITPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getTrackid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getAlbumid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getMediatypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getGenreid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getComposer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getMilliseconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getBytes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getUnitprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTrackid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAlbumid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMediatypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGenreid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getComposer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getMilliseconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getBytes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getUnitprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord value1(Integer value) {
        setTrackid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord value3(Integer value) {
        setAlbumid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord value4(Integer value) {
        setMediatypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord value5(Integer value) {
        setGenreid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord value6(String value) {
        setComposer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord value7(Integer value) {
        setMilliseconds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord value8(Integer value) {
        setBytes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord value9(BigDecimal value) {
        setUnitprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TracksRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, String value6, Integer value7, Integer value8, BigDecimal value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TracksRecord
     */
    public TracksRecord() {
        super(Tracks.TRACKS);
    }

    /**
     * Create a detached, initialised TracksRecord
     */
    public TracksRecord(Integer trackid, String name, Integer albumid, Integer mediatypeid, Integer genreid, String composer, Integer milliseconds, Integer bytes, BigDecimal unitprice) {
        super(Tracks.TRACKS);

        set(0, trackid);
        set(1, name);
        set(2, albumid);
        set(3, mediatypeid);
        set(4, genreid);
        set(5, composer);
        set(6, milliseconds);
        set(7, bytes);
        set(8, unitprice);
    }
}
